### PR TITLE
remove extreme feminist / SJW bullshit. This creates an overall friendlier atmosphere

### PR DESCRIPTION
**Pull request by goodwolf**
There's no need to allow hate or harassment from any individual regardless of disadvantage. If anyone wants to be taken seriously, they need to create an overall friendly atmosphere by not allowing any of the vile intolerance.

### CODE REVIEW

**Comment by ghost** [comment]
Agreed. Tolerance breeds tolerance. Resentment breeds resentment. Bullshit breeds bullshit.

**Comment by goodwolf** [comment]
I'm adding this statement so this can be placed in this pull request on the @todogroup's repository.

## My statement to the community

While those who constructed the CoC clearly don't have any legal background, I can tell you much of what is in the Code of Conduct will end up leading to civil lawsuits. I'm a person who can speak more about oppression more than any feminist in STEM and have taken various actions in the past.

This is also a promise to the community: I will file a civil lawsuit if there are any negative acts based on my ethnicity, sexual orientation, gender or sex. Some of my actions are quite open to public record, just as I've battled government entities who attempted to enforce an unlawful ordinance. The fine was a $25 summary offense, however the voracity of the charge was quite distasteful.

If anyone wants to discuss the lawful and unlawful implications of this code of conduct along with past case law relating to racial discrimination, feel free to reach out. There are cases where racial discrimination have been found unlawful and lawful depending on the situation.

I'm extremely open to discussion and debating, I prefer to base my statements and actions on facts instead of feelings. Rest assured any discussions will encourage unifying communities instead of breeding a web of distrust.

**Comment by ghost** [comment]
I don't think there'd be too many civil cases over this CoC. There's been that much of a backlash against this that no-one will want to adopt it in its current form (I hope). Even Twitter decided to water down the inflammatory parts of the CoC (Twitter/code-of-conduct).

Does that make any of this right? Of course not. I just don't think it will wind up in court any time soon.

**Comment by ghost** [comment]
It was @ammeep who added the original mention of "reverse-isms". This was done in b00eff579ded8c76cee0d2cb6b5beed6e84258fb, met with a wonderfully condescending "(because these things don’t exist)".

This is a member of GitHub staff who is perpetuating this nonsense for crying out loud.

**Comment by davblayn** [comment]
I stand mistaken, Matthew Hopkins is doing something http://matthewhopkinsnews.com/?p=2055

**Comment by goodwolf** [comment]
Civil lawsuits mat occur if there are any acts relating to official business, which by definition is more than mere employment. Anyone partnered, engaging in business or relations of any kind with a company enforcing the CoC will be at risk of lawsuit.

I will be creating a write-up on various to ensure there will be proper action. I'm already collecting information to create a guide and also describe specifics where racial / sexual discrimination is lawful vs unlawful. The best way to combat this sort of extremism is to make sure everyone is informed with facts instead of interpreting the situation with emotions.

**Comment by ghost** [comment]
I won't be holding my breath for a lawsuit.

**Comment by goodwolf** [comment]
@davblayn Many times revealing how this sort of behavior from @Github can create lawsuits will be enough. If not, then lawsuits will be pushed ahead. I will certainly be one of those who will be contacting the capital firms as they will certainly not be amused. I'm accustomed to working with a variety of people, including capital firms and investors. When a company like Github, Box or others attempt to create a hostile atmosphere in threat of lawsuit then said firms tend to send out the dogs.

Remember people, there's no such thing as being/imaginging you're too big you can't possibly fail. That being said even though GitHub is well known, they're certainly not "big" by my standards.

**Comment by ghost** [comment]
I have half a mind to switch to Bitbucket because of this. In fact, I think I will.

**Comment by goodwolf** [comment]
@davblayn I've been using bitbucket for years. Until the recent story where someone wanted to go PC over the project "WebM for Retards," I was inclinded to start using GitHub to publish some of my chef repos and projects I want to release. The ridiculous nature of @bkeepers, @caniszczyk and @defunkt has swayed me to also move some projects off Github on to Bitbucket and/or on-site.

edit: @caniszczyk, not @cra

**Comment by ghost** [comment]
@goodwolf Do you want to continue this conversation over email rather than on the issue page of the very repository we're criticizing?

**Comment by goodwolf** [comment]
@davblayn sure, you can contact me at connor.goodwolf@wolfeon.com

**Comment by ghost** [comment]
Got it. Now scrub everything before we get doxed.

**Comment by goodwolf** [comment]
@davblayn I couldn't give a shit if people want to dox me, my information is publicly out there. People know while I attempt to create the most friendly and efficient settings, the reciprication and resolve is 10x fold of any attack. Why do you think I'm posting publicly under my name instead of an anonymous account?

**Comment by ghost** [comment]
True, true.

**Comment by ghost** [comment]
Well, I'm deleting my account now and moving to Bitbucket. This has all been a calamity.

**Comment by ghost** [comment]
I'm back.

**Comment by bkeepers** [comment]
Thanks for your feedback. See #84.

**Comment by cra** [comment]
[I just wanted to state that someone with a nickname cra they mention here is not me and, therefore, not @cra on github]

**Comment by goodwolf** [comment]
My apologies @cra, I meant @caniszczyk who uses the handle "cra" on twitter.

**Pull request closed without merging**
