### PR TITLE
remove "religious" and "political" from the list of offensive comments which can be harassment

### PR DESCRIPTION
**Pull request by sheepdestroyer**
As stated here : todogroup#75
the meme version : https://pbs.twimg.com/media/B7Wz261CIAAQLs4.jpg:large

While all other traits are intrinsically constitutive of the person, religion is only an opinion that anyone is free to change at anytime.

I do not welcome or advocate discrimination and harassment of people for their beliefs.
I really believe in respect of the person (and that it must be enforced), but do not think opinions are worthy of such respect. That would in fact be a dangerous idea for liberties.

However as stated in the policy now, it becomes harassment to merely offend religious people. That is extremely wrong. Religious people can chose to be offended by anything. According a "right not to be offended", is going counter to all advance by modern societies. Is is very wrong and very dangerous to put religions (just an other opinion) on the same level as intrinsic properties of what a person is : sex, genre, race, etc...

Historically (and still very much now!) religions have been the primary sources of obscurantism and persecutions. Societies fought back and began separating states and religions, according a right to blasphemy in many cases. The right to blasphemy has been primordial in freeing people from the control of churches.

Nowadays, we see a weakening of the Age of Enlightenment's philosophical advances : https://en.wikipedia.org/wiki/Age_of_Enlightenment
Religious groups everywhere try to weaken once again civil liberties by asking for this right to be offended and to forbid blasphemy.

Letting them having their way redefining what is socially acceptable would be a moral and philosophical regression. Accepting this would not be fighting against discrimination but calling for it.

Also, the word political was also removed because I honestly think that even if saying that "Nazi were dumb shit" may be offensive to Nazis, it is no harassment either.
Also, they are free to, and I hope would, change their mind as it is just opinions once again, not defining who they are as humans (I am an optimistic humanist).

### CODE REVIEW

**Comment by CoWinkKeyDinkInc** [comment]
> Religious people can chose to be offended by anything.

All of the major religions have specific definitions of what is offensive or wrong, or how it can be justified in certain situations.  The most important of these rules are already in here anyway.

**Comment by sheepdestroyer** [comment]
As you quoted, I said religious people not religions. Most variously interpret their own sacred texts according to the feeling of the day.

**Comment by CoWinkKeyDinkInc** [comment]
By who?

**Comment by sheepdestroyer** [comment]
- Some do take the 6000 years thing for hard evidence. But you do know that not all christians are creationists.
- It is repeatedly stated by scholars that nothing in the quran makes the veil necessary, many will have a progressive interpretation, but you still have those who would like to cover every women. 

etc, etc ; it's not as if the texts where very precise anyway - That is why care not to offend their believers should not even be attempted. This thinking that religious should not be offended in their belief would lead strait to more discrimination and intolerance.

**Comment by CoWinkKeyDinkInc** [comment]
This avoids my question to your response that you recently edited.  But then again I took this seriously when you said things such as:

> strait back to the middle age
> 
> Religious groups everywhere try to weaken once again civil liberties by asking for this right to be offended and to forbid blasphemy.
> 
> Historically (and still very much now!) religions have been the primary sources of obscurantism and persecutions

This statement below is already a contradiction.

> I do not welcome or advocate discrimination and harassment of people for their beliefs... but do not think opinions are worthy of such respect. That would in fact be a dangerous idea for liberties.

You already assume that religions are dangerous and that ideas if I'm taking the meme link seriously, don't have rights when the freedom of speech grants every person and idea a voice.  Like what you think most religious people do, you are interpreting the text included in the OCoC to fit to your idea that religions are inherently dangerous and that this will allow them to be offended by "everything".  The fact that you made this pull request literally three hours after you tried to do this in #75 and copy-pasted every statement from there just proves you know that you are trying to twist it's words and want to remove it.

Religions are beliefs that should be considered with respect as any other opinion.

:-1:

**Comment by sheepdestroyer** [comment]
I see no contradiction and 
No, I do not assume that all religion are dangerous, merely that some interpretations of their religions can be. Ideas, political or religious or any kind, need to be disposed to criticism, how offending that may be to those who believe them.

That way leads to godwin law... You are not without knowing that as well as fascist religious extremists on one side, extreme right activists are also on the rise once again... But we should respect both?

Beliefs/opinions should not be considered with respect. Or nazi beliefs should also?

**Comment by sheepdestroyer** [comment]
An other meme : https://i.imgur.com/2YqJfZ2.jpg
From someone who is persecuted and and whose life is endangered by religious extremists feeling offended.

**Comment by Addvilz** [comment]
This list must be interpreted using common sense, not finding "last straws". What is meant with "political or religious affiliation" is that community should not exclude, for example, a republican or Muslim just because someone or even majority of that community consists of democrats or Christians.

It is a basic human right to exercise religious and political beliefs, while not being ridiculed about them. This is a statement against discrimination, it is not a grant of privileges.

So instead of reading this like "I can't say anything about X religion because that might offend someone", instead you should read it like "I can't call religion X and followers _insert Pulp Fiction levels of swearing here_, just because I felt like doing so for no reason"*.

*Terms and conditions of common sense applies.

**Comment by sheepdestroyer** [comment]
I understand and agree that - followers - of any religion are not to be sworn at. As any human being  they deserve respect. 

However, if for example someone would like to say/draw/express ridicule things about an imaginary friend in order to satirize/criticize said belief, some could (and many wrongfully do) take personal offense even if the attack is directed not at them but at said belief. Thus cutting debate and preventing speech. 

That is the fundamental difference about respect of people versus opinions, and why the latter needs to be avoided.

**Comment by CoWinkKeyDinkInc** [comment]
> ridicule things about an imaginary friend in order to satirize/criticize said belief, some could (and many wrongfully do) take personal offense even if the attack is directed not at them but at said belief.

You literally said there is something wrong with them for believing in their religion.

**Comment by sheepdestroyer** [comment]
No, you do not understand grammar? I said It is wrong to personally take offense for criticism of your belief, not to be religious in the first place.

First because there is no right not to be offended in that case. Your party or religion being mocked is just that, it's not you being mocked.

As a believer whose religion (it is also true for any other kind of opinion or idea, political, etc...) got mocked or criticized, there are three options: 
- You can agree to disagree. 
- You can be convinced of changing belief. And that was is great with debating ideas. Try that with your race, you can't . Because you race, sex, sexuality, etc..., are what you are. What you think is not.
- You may also convert your opponent instead!

As religion or political belief are just opinions, they are not intrinsically constitutive of your person. You are born black or asian, but chose to become communist or buddhist. And still free to change your mind anytime at the cost of reflection only. There are numerous examples of people changing political party, being converted to other religions or simply dropping them. That's is the power of debate and criticism. 

For instance, as an optimist humanist, I do no hate xenophobic right wing extremists because I know (and hope) they can be convinced to change. I only despise their _current_ ideology. 

That is why ideas are way different than race, sex etc ...and should never be treated the same.

**Comment by CoWinkKeyDinkInc** [comment]
For an optimist you think "the right not to be offended" is going halt all advances of modern society and bring us straight back to the middle ages.

And for the Nazi part that you mentioned, come on; they are already not permitted under racism, homophobia and anti-antisemitism, the latter of which is something you want removed under this pull request of "religious-allficiation".  You have also edited your previous comments again, which just proves that you can't even keep your arguments and opinions straight.  At this point, you are trying to not understand what the words you want remove even means under it's context.

*tips fedora*

**Comment by sheepdestroyer** [comment]
Yes, i do believe this new right not to be ofended is contrary to modern socities. Please Read about Salman Rushdie and philosophical advances made during the age of enlightenment.

As for editing my posts, I struggle with english wich is not my language. I realy want to carefully pick my words as I want to be clearly understood. I guess I do not do such a good job at it, even with edits, cause You still manage to put words in my mouth wich are contrary to what I belive.

**Comment by CoWinkKeyDinkInc** [comment]
If you do struggle with English, which I find hard to believe, than who are you telling me that I don't understand grammar?  This conversation is over.

**Comment by sheepdestroyer** [comment]
Who am I? Someone who puts lot of efforts to be precise clear and understable, and I expect as much effort from your part to understand me.
Your are the one who told that I "said there is something wrong with them for believing in their religion". This is not the case and is in fact contrary to what I stand for.

This is not the way of an honest debate, i expect more effort to at least corectly understand my point, and not misconstructing it

**Comment by Addvilz** [comment]
I still don't see any relevance of what you say to what this list has defined. It says "Offensive comments related to [...] political or religious affiliation". Nowhere does it say "Offensive comments related to political or religious practice" - yet when I think of it, it probably should.

If you have valid criticism against religion in a context that actually has something to do with religion, you are welcome to execute your rights and criticize all you want.

Second to that, intentionally pissing people off just because you have nothing better to do with your life isn't anything anyone should be encouraging, nor practicing. And you can not base your argument of essentially taking away a basic right to be free to believe whatever one wants to believe with a fear of being retaliated for mocking people.

Mocking or harassing an Idea or followers of given idea for no reason other than your personal views and beliefs is not acceptable, and it even has a few terms describing such actions - totalitarianism and plain old a-hole`ism - e.g. what you have been doing for this entire thread. And I am saying that as an person who is agnostic, so you wouldn't think that my opinion is somehow influenced by my religious beliefs or lack thereof.

Enough is enough.

**Comment by sheepdestroyer** [comment]
Mockery of religion has not historically been used by those in power to discriminate minorities but on the contrary has been used by secularist minorities to undermine and free themselves from the prevalence of (state) religion.

For example, blasphemy and satirized mockery of the clergy was notoriously influential in separation of church and state in France and the fight to pass 1905's law.

As such, they are tools of freedom and anti-totalitarianism, and would still be plenty useful for those living in such countries today (and to prevent old ones to win back a so called right to be respected where such thing is luckily not recognized anymore).

Calling my discussion "totalitarianism and plain old a-hole`ism" is to be seen nice talk I guess? 
That's very much uncalled for, and ironically, can not be more the exact opposite of what the evoked principles stand for.

**Comment by Addvilz** [comment]
> For example, blasphemy and satirized mockery of the clergy was notoriously influential in separation of church and state in France and the fight to pass 1905's law.

Not that it matters much, because nothing you said bears any relevance to changes you made, but can you link to at least few authoritive sources to back this up?

Mockery of something is never tool of freedom and anti-anything, and never has been, it is a tool of either a) belittling b) entertainment and previous. 

And you are still missing the point - the wording you removed is to prevent criticism against individual affiliation, not the subject individual is affiliated to. Hence, none of your arguments you made are relevant, nor valid.

**Comment by sheepdestroyer** [comment]
Satiric press really started flourishing during the french revolution and is a direct emanation of the age of enlightenment's philosophers evoked before.It started mocking the king and was determinant making the people take arms against monarchy. Since then it has endlessly took on those in power, clergy included. Read up about it's influential role in social struggles: 

https://fr.wikipedia.org/wiki/Presse_satirique
https://fr.wikipedia.org/wiki/La_Calotte
https://fr.wikipedia.org/wiki/L%27Assiette_au_beurre
http://www.akadem.org/medias/documents/3_caricatures.pdf

**Comment by sheepdestroyer** [comment]
I would add that contrary to what you said, mocking the ruling (political, moral, religious, etc) powers is very much an effective tool (by yes, belittling and entertainment) for those subject to these powers to undermine the sense of sacredness and thus fight on a more even field. 

Again, see french kings ; "L'assiette au beurre" and "La Calotte" for specifics about 1905 ruling.

**Comment by Addvilz** [comment]
Satire has been around for thousands of years, has many forms, and has served many purposes, including social causes. The fact that at some point in history something worked in favor of an idea and therefore should also be accepted in current time per se is sweeping generalization. Many things have happened during the history of human kind, some exceptional, some factors dependent.

In addition to that, I see two problems here - not all of us speak French, hence, linking a French wiki isn't really helpful to anyone except me and you maybe. Although your point point might be valid, assumption of which can be debated, I still don't see what has this to do with the argument at hand - it is a false attribution and serves no purpose other than avoiding the root problem of this PR.

**Comment by bkeepers** [comment]
Thanks for your feedback. See https://github.com/todogroup/opencodeofconduct/issues/84.

**Pull request closed without merging**
