### PR TITLE
Solves conflicting statements

### LINKED ISSUE #40: Contradictory Language
Quoting the "Definitions" clause of the CoC:

> Harassment includes, but is not limited to:
> 
> - Offensive comments related to gender, gender identity and expression, sexual orientation, disability,
> mental illness, neuro(a)typicality, physical appearance, body size, race, age, regional discrimination,
> political or religious affiliation

This somewhat contradicts the passage explicitly saying we don't accept complaints of these so called "reverse"-isms, and that we prioritize oppressed people over the privileged  

> Our open source community prioritizes marginalized people’s safety over privileged people’s comfort. We will not act on complaints regarding:
> 
> - 'Reverse' -isms, including 'reverse racism,' 'reverse sexism,' and 'cisphobia'

### PR DESCRIPTION
**Pull request by MrsTonedOne**
Since we are gonna just use discriminatory and unwelcoming and unfriendly language in the CoC, and any attempt to remove them gets closed, we shouldn't have such clauses now should we?

If you didn't want the conversation to start in bad faith, you shouldn't have used discriminatory and unwelcoming language in your CoC.

Fixes #40

### CODE REVIEW

**Comment by NuckChorris** [comment]
This isn't funny any more. It's just sad. Calm down and we can discuss

**Comment by MrsTonedOne** [comment]
I am calm. But up till now, no discussion has been allowed.

**Comment by NuckChorris** [comment]
It's allowed, over on #40

**Comment by MrsTonedOne** [comment]
I made a PR to fix it, That pr has not been allowed to carry a discussion. How about we just re-open #49 So I can close this on, and move on with the discussion.

**Comment by lfaraone** [comment]
As explained previously, discussion should continue on #40. Opening numerous issues and pull requests after being asked to stop is disruptive.

**Pull request closed without merging**
