### PR TITLE
Removes unwelcoming language

### LINKED ISSUE #40: Contradictory Language
Quoting the "Definitions" clause of the CoC:

> Harassment includes, but is not limited to:
> 
> - Offensive comments related to gender, gender identity and expression, sexual orientation, disability,
> mental illness, neuro(a)typicality, physical appearance, body size, race, age, regional discrimination,
> political or religious affiliation

This somewhat contradicts the passage explicitly saying we don't accept complaints of these so called "reverse"-isms, and that we prioritize oppressed people over the privileged  

> Our open source community prioritizes marginalized people’s safety over privileged people’s comfort. We will not act on complaints regarding:
> 
> - 'Reverse' -isms, including 'reverse racism,' 'reverse sexism,' and 'cisphobia'

### PR DESCRIPTION
**Pull request by MrsTonedOne**
Fixes #40
PR that introduced the removed content: #17 
Edit:

The intent of this pr is to preserve the welcoming nature of the repos that use it. Regardless of any discussion or debate on rather reverse racism exists, or any discussion or debate on the exact definition of discrimination, language that excludes entire classes from anti-discrimination clauses creates an unwelcoming, impolite, and potentially hostile environment. 

I should probably ping @ammeep in here, since it is their change that is getting partially reverted.

Edit:
This thread has been locked, because that is literally meaningless:
# Feel free to continue discussion at: https://github.com/MrStonedOne/opencodeofconduct/pull/1

**_I will edit all comments from there into this comment**_ (maybe some day @bkeepers will learn that you just can't stop the signal, you can never stop the signal.)

---

---

just3ws:
+1

---

thor:

> The intent of the open code of conduct is to help establish communities that are safe and welcoming for _everyone_. At some point, the moderators of a community are going to have to make tradeoffs. The language in question is attempting to guide how those tradeoffs are prioritized, not to encourage hostility.

I am having a hard time seeing how creating a biased discrimination filter creates a safe and welcoming community for _everyone_ -- would it not be ideal to establish a absolutely fair and even set of guidelines that apply to _everyone_ if one wants _everyone_ to be equally safe and welcome? :unlock: 

> [..] if we can clarify the language to communicate that.

Hopefully there is a way to clarify that without imposing perceived biases on communities as a default?

---

MrStonedOne:
@bkeepers:

> The intent of the open code of conduct is to help establish communities that are safe and welcoming for everyone. 

Yep! Everyone.

> At some point, the moderators of a community are going to have to make tradeoffs. 

[citation needed] You disallow discrimination, and you disallow discriminatory language, no trade off necessary.

> The language in question is attempting to guide how those tradeoffs are prioritized, not to encourage hostility.

Again, not needed. There are no tradeoffs involved, this isn't a zero sum game.

> I will seek feedback from people that have been invested in crafting and adopting this document to see if we can clarify the language to communicate that.

And I'm going to insist that there is no way such "priority" can co-exist with a safe and welcoming environment.

> I am also going to lock this thread while I do that.

I see no need for this, and it's easily thwarted. This seems like you trying to ensure you got the final word in.

> Know that your feedback is being taken seriously.

Heh. Is that why you locked the pr in an attempt to ensure your privileged position in the discussion. Get the final word in, and call it good. "but know that your feedback is being taken seriously" The tried and true words of people who want to silence criticisms they aren't comfortable with.

---

ELLIOTTCABLE:
Wow, this is fucking ridiculous.

The creators and maintainers of _this project_ have made themselves clear to you, @MrStonedOne (your name, too … just, wow.) They offered to take your concerns seriously (more, by the way, than they are _in any way_ obligated to do), but it's entirely their right (and a damned good decision) to shut down the potentially-unproductive discussion while they decide whether they're compfortable making those changes.

This is an open-source document; you're welcome to fork it, if the maintainers end up disagreeing with you; and tell people of your concerns with the original / point out your forked efforts at improvement.

Pulling _this_ “ooo my freedom of speech is being quashed!!1!” stuff is a really good way to get those concerns ignored completely. Well done, sir, well done.

---

MrStonedOne:

> Pulling this “ooo my freedom of speech is being quashed!!1!”

Actually, I said they tried to stop discussion, nothing about free speech.

> your name, too … just, wow.

Some people drink alcohol, they might even make a username on that, some people smoke weed (and they too might make a username on that) I see no issue, it's all 21+ legal, so whats the issue? I'm over 21(25), I am legally allowed to smoke marijuana, and I refuse to make it a secret part of me because somebody wants to use it as an excuse to look down at me. 

---

KelseyDH:
:+1: 

---

apullin:
:+1:

In the other threads, I have seen it stated that it is a non-starter to discuss the material nature of the items being removed. There should be a motion for estoppel with whichever pertinent committed or governing bodies for the project, with respect to the inclusion of any disputed elements being included. Hiding one dispute behind another is poor design and leadership.

If GitHub intends to adopt this policy, then I am de facto directly involved with it, as I have made agreements, both contractual and financial, with GitHub. The is true for organization that stated intent to adopt this document, and for any persons who have any transactions or contracts with them.

@ELLIOTTCABLE, you are personalizing this is a fruitless way. I am certain that I have done myself this with difficult issues in the past. I only offer this to try and level the hotness of the personal politics that pervade this issue.

---

tkerber:
:+1:

I cannot see myself contributing to any project using the open code of conduct unless this is removed.

I do not think that todogroup should inject their own ideology into a document which is supposed to protect **people**.

---

ceph3us:
:+1:

The spirit of open source is to allow equal access to all without qualification or discrimination, and a company whose business in invested in it should follow those principles. A community seeking to be accessible to everyone should not promote a one way street on the policing of negative behaviour.

---

Karunamon:
+1

This kind of nonsense seriously impacts my desire to use Github for any projects, personal or otherwise, in the future. It's clear the site leadership values ideology more than Getting Shit Done©

---

arthurkay:
Codes of conduct are not a means for legitimizing people being abusive online. They're meant to stop that. And the old Open Code did. Please do not grant special protections to abusive users like https://github.com/freebsdgirl

---

j-wo-:
:+1:

This kind of language only serves to antagonize every person who does not share the ideology of the authors, and it would be foolish for any project to alienate a great number of people by including it.

### CODE REVIEW

**Comment by thor** [comment]
:+1:

**Comment by NuckChorris** [comment]
I have to agree that outright exclusion is probably the wrong approach. That said, we probably need to find a safe balance between equality and the acceptance that some people feel unsafe. Whether they are or aren't is irrelevant, what matters is that they feel that way.

Perhaps a simple change of wording from completely ignoring to something less "heavy"?

**Comment by MrsTonedOne** [comment]
It is still unwelcoming to state that you will treat reports of discrimination differently based your perceived perception of their minority status. The language just complicates things, gives the CoC a unnecessary western centric approach, and flat out has no merit other than to be used to create a selectively unwelcoming environment based on what the repo's owners decide is the majority/minority line.

**Comment by NuckChorris** [comment]
In an ideal world, their privilege would be irrelevant and the complaints anonymized, but we're not in an ideal world.

There's some people who feel less safe than others, and we need to accept this and account for it.

That is, some people who feel safe easily give up some sense of comfort so that people who don't feel safe easily can feel safe enough to contribute. Yes, that does mean that it's slightly less welcoming to some people.

My understanding is that this was in here to make that explicit. Removing it defeats that purpose.

It sucks, it's a hack. But we're programmers. We're all about hacks.

**Comment by MrsTonedOne** [comment]
> Some people who feel safe easily give up some sense of comfort so that people who don't feel safe easily can feel safe enough to contribute.

I'm not sure how the two relate. What this clause does, is state that reports of discrimination will be ignored if the person is believed to be too privileged by repo maintainers. This in turn openly states that such people are open season for discrimination, or at least, that's how unsavory people are going to interpret it. It also doesn't state where on the macro/micro line this applies, could somebody use this as a cover for their misogynistic language in a repo or organization ran by mostly women?

It's inviting unnecessary rules lawyering.

Any benefit it might bring is already pretty explicitly covered in multiple parts of the CoC. Its just not worth the trouble.

> There's some people who feel less safe than others, and we need to accept this and account for it.

This is 100% subjective, and changes person to person, not race to race or gender to gender. Some women will be able to safer than others in some kinds of hostile environments better than other women.

Same goes for men, same goes for every race on the spectrum,

If you are arguing that people should be expected to respond to certain situations based on how your perceived race or gender roles says they should respond, I think you might want to re-evaluate that viewpoint. ok, I doubt that's how you intended that, but that's the logical conclusion of that argument.

So either we remove the clause, and respect the individual, and the fact that their life experiences, (that are going to exist outside of the vacuum of the open source community and its gender/racial makeup) are going to determine how safe they feel, not just their race or sex or sexual orientation or gender identity.

Or we keep it, and state to people reading it, that they are only allowed to feel as unsafe as some middle aged middle classed western people writing the CoC said they should.

**Comment by AFFT-520** [comment]
+1

Hatred is hatred, and we should not tolerate it against anyone, no matter how 'privileged' you think they are. As it stands we literally have one rule for blacks, another for whites, one rule for men and another for women. That is not equality. This CoC is supposed to be welcoming for all, not just the people Tumblr likes.

**Comment by seanodonnell** [comment]
+1

**Comment by DorthLous** [comment]
:+1:

**Comment by TheLoot** [comment]
MrStonedOne, you're slightly off on a point.

This isn't about repo maintainers thinking someone is "privileged", it's about they being biased and prejudiced against certain people. The "privilege" argument is an excuse for sexist and racist behavior, and it's pretty clear when people of that sort use those weasel words, it's because they're trying to shield their own bigotry.

Completely behind this change, but it's pretty clear the entire "Open Code of Conduct" is based on the aforementioned ideologies, so this thing is dead on the starting line: even if those lines are removed, the types that would enforce this CoC are the type to do it anyways.

**Comment by MrsTonedOne** [comment]
My goal with doing it that way is to point out that outside of any arguments on reverse racism, it's still a bad clause.

IE: basically sidestep that entire mess of a debate, because it doesn't matter.

**Comment by MrsTonedOne** [comment]
> but it's pretty clear the entire "Open Code of Conduct" is based on the aforementioned ideologies

It's not, that section came from geek feminism, While GF has their own issues with discrimination from within GF, everybody who takes example work from them doesn't necessarily have the same issues. It could be ignorance, as I'm sure it is in this case.

**Comment by An-Annoymous-Developer** [comment]
Let me be completely blunt. 

I am one of the marginalised people this code of conduct is trying to prioritise. Ethically I'm a mixture of German-Jewish, Bulgarian-Jewish, and Polish-Jewish. Two generations ago my family were penniless refugees fleeing prosecution or, well most of them were dead.  

This language @MrStonedOne wishes to remove is quite simply saying people are more acceptable as targets because of their their race, religion or sexuality. After how I was raised and what I was taught about my families history, I could **never** feel comfortable and would **never** attend any conference that said any group is a more acceptable target; not even a hint in that direction. 

I support this pull request.

**Comment by ghost** [comment]
Hate is hate, no matter who does the hating.

**Comment by MrsTonedOne** [comment]
@An-Annoymous-Developer could you specify your point a little, When you say `This language is quite simply saying people will be judged by their race` what do you mean by `this`? The removed bit of text in the pr, or something that was said/suggested in the comments of this pr?

**Comment by An-Annoymous-Developer** [comment]
@MrStonedOne 

Yeah. After I had a chance to, metaphorically, count to ten I realised my comment wasn't as clear as it could be and so I went back and edited it. 

I am referring to the language that your pull request will remove. Make no mistake, I am 100% in support of this pull request and thank you for raising the issue.

**Comment by MrsTonedOne** [comment]
I figured as much, but I like to ensure everybody understands everybody when possible.

"Seek first to understand, then to be understood"

**Comment by An-Annoymous-Developer** [comment]
And you're right to do so. 

A purely text based medium is too easily misunderstood, allays err on the side of asking for clarification.

**Comment by MrStonedOne** [comment]
I should probably ping @ammeep in here, since it is their change that is getting partially reverted.

**Comment by bkeepers** [comment]
The intent of the open code of conduct is to help establish communities that are safe and welcoming for _everyone_. At some point, the moderators of a community are going to have to make tradeoffs. The language in question is attempting to guide how those tradeoffs are prioritized, not to encourage hostility.

I will seek feedback from people that have been invested in crafting and adopting this document to see if we can clarify the language to communicate that. I am also going to lock this thread while I do that. Know that your feedback is being taken seriously.

In the mean time, this code of conduct is a template. You are encouraged to fork it and adapt it to the values of your community.

**Comment by bkeepers** [comment]
Just to update everyone, I am still working with those that have been invested in this effort to clarify the language and hope to have some edits posted for discussion soon. Thanks for your patience.

**Comment by bkeepers** [comment]
Updated plans for next steps outline in https://github.com/todogroup/opencodeofconduct/issues/84.

**Pull request closed without merging**
