### PR TITLE
Make placeholders configurable

### PR DESCRIPTION
**Pull request by bkeepers**
The Code of Conduct will gain more adoption if it's easy for maintainers to adopt it. Some projects may still want to fork it and make more drastic changes, but for a significant portion of the community, the standard template will suffice. This is an attempt to demonstrate what was suggested in #7:

configure

_Updated gif, [here is the original](https://cloud.githubusercontent.com/assets/173/8343205/8a6c3594-1a98-11e5-93a8-ede262a98b14.gif)_

If we want to go this route, there's still some more work to do here:
- [x] Clean up the JavaScript
- [x] Design it
- [x] ZeroClipboard to make it easier to copy the snippet
- [x] Better way to encode config data

What do you think?

/cc @caniszczyk

### CODE REVIEW

**Comment by mislav** [comment]
I'm a fan of how this was executed. :+1: 

I'm not a fan, though, of the user's perspective: how this generates URLs that seem to have robot barf in it. URLs with big fragment values that carry important data generally don't fill me with confidence.

**Comment by bkeepers** [comment]
I agree. Here are a few ideas to make this better:
- use normal params: `?community=Foobar&email=abuse@example.com`
- continue using the anchor, but make it cleaner: `#Foobar,abuse@example.com`

**Comment by bkeepers** [comment]
I made a few tweaks to the design. It could use a real designer at some point, but this highlights what I was envisioning.

[GIF](https://cloud.githubusercontent.com/assets/173/8435483/6c1ce8e6-1f1f-11e5-9723-92ec1de3c9de.gif)

**Comment by bkeepers** [comment]
@mislav I updated this to use this url format: `http://opencodeofconduct.com/#ProjectName/email%40example.com`. Thoughts?

**Comment by mislav** [comment]
Looks great (both design and URL path).

Even if query parameters in the URL are human-readable, I think seeing them betrays that this text has been auto-generated and that might make the CoC feel less personalized and less legit. I'm just speaking for myself here.

**Comment by mislav** [comment]
Here's how to copy contents of a `<input>` element without Flash in Chrome 43+ and Firefox 41+:

``` js
input.select()
document.execCommand('copy')
window.getSelection().removeAllRanges()
```

**Comment by bkeepers** [comment]
Alright, I'm pretty happy with where this is at. I would love feedback or suggestions on what else is needed. There are some changes I need to push to the todogroup.org styles to make this work, but I'll get a PR open for that so we can merge both at the same time.

/cc @caniszczyk @amateurhuman @mislav 

configure

**Comment by mislav** [comment]
If you're going to have magic copy behavior, you have to make the users know. Otherwise they probably won't figure it out by themselves. Maybe it's best to have an explicit “Copy to clipboard” button.

**Comment by caniszczyk** [comment]
Hell I actually like it! I think it's good enough to start with, we can iterate later and making it a bit fancier. Some people will use this functionality, others will simply copy the index.md

**Comment by bkeepers** [comment]
@mislav thanks for all your feedback. It's live: http://todogroup.org/opencodeofconduct/

One thing I think we'll want to tweak is the snippet that gets copy and pasted into the project. Since tons of projects will have this, we'll want to make sure it's well-worded:

> This project adheres to the [Open Code of Conduct](http://todogroup.org/opencodeofconduct/#Atom/abuse@atom.io). By participating, you are expected to uphold this code.

**Pull request merged**
