### PR TITLE
Link to explicit definitions of harassment

### PR DESCRIPTION
**Pull request by caniszczyk**
Related to the request from @ammeep:

https://github.com/todogroup/opencodeofconduct/pull/17

Signed-off-by: Chris Aniszczyk zx@twitter.com

### CODE REVIEW

**Comment by Addvilz** [comment]
There exists a widely accepted definition of harassment already, which can be quoted here. Given link and contents of it is superfluos and biased. 

"To harass - to create an unpleasant or hostile situation for especially by uninvited and unwelcome verbal or physical conduct" http://www.merriam-webster.com/dictionary/harass

**Comment by ammeep** [comment]
The definition of what constitutes harassment or or hostile situation, is extremely important. More important than this are the definitions of what does not constitutes harassment or or a hostile situation. 

The advantage of behind being explicit is that we specifically protect those who are impacted by hostile environments.  

We **need** to prioritize marginalized people’s _safety_ over privileged people’s _comfort_. I'm of the view that this is the purpose putting **any** code of conduct in place. This is not a footnote - it is the reason behind needing a code of conduct. 

If you don't mind @caniszczyk I would :heart: if we could take the linking approach off the table?

**Comment by Addvilz** [comment]
> The advantage of behind being explicit is that we specifically protect those who are impacted by hostile environments.

You mean, everyone? Or are you trying to say that only few, chosen  groups are subject to hostility and others are not? Who or what is going to decide which ones and why?

> We need to prioritize marginalized people’s safety over privileged people’s comfort. I'm of the view that this is the purpose putting any code of conduct in place. This is not a footnote - it is the reason behind needing a code of conduct.

This statement does not make any sense. What we need as a community and society in general is to prioritize everybody's safety, equally. Otherwise, what you are basically saying is "let's have equality, but let's take a few groups and make them more equal than others". 

The reason behind needing code of conduct is to "set the ground rules for participation in communities, and more importantly [to help] to build a culture of respect and improve diversity", as quoted from the README. Your argument clearly and unambiguously divides community as a whole and places exempt privilege on exempt groups - this does not help with building diverse communities, nor does it help to build culture of respect, it promotes culture of exclusion and bias.

**Comment by jglovier** [comment]
> > We need to prioritize marginalized people’s safety over privileged people’s comfort. I'm of the view that this is the purpose putting any code of conduct in place. This is not a footnote - it is the reason behind needing a code of conduct.
> 
> This statement does not make any sense. What we need as a community and society in general is to prioritize everybody's safety, equally. Otherwise, what you are basically saying is "let's have equality, but let's take a few groups and make them more equal than others".

@Addvilz the sense in the original statement is that while everyone should be able to enjoy equality and safety, to approach the issue in a blanket way fails to acknowledge that there is an unbalanced side to safety and equality which needs to be compensated for. Those who are marginalized do in fact need extra protection from those who would discriminate against, harm, or otherwise further marginalize those people, by very definition of the problem.

**Comment by bkeepers** [comment]
#17 was merged.

**Pull request closed without merging**
