### PR TITLE
Replace language targeting groups with general principles

### PR DESCRIPTION
**Pull request by An-Annoymous-Developer**
At the end of pull request #56 @bkeepers explained the thinking behind this template code of conduct. 

In the interest of being constructive in my criticism here is my proposal for a CoC that fits his aims. If @bkeepers wishes to lock this comment thread too pending the unlock of pull request #56 - then be my guest. 

---

My goal with this was to not single out any particular group as being an "acceptable target", to me even the concept of someone being an acceptable target is enough to make a convention feel actively hostile. 

I believe this captures as much of the original intent as possible without explicitly referring to any group. 

(tagging in @MrStonedOne @ammeep )

### CODE REVIEW

**Comment by NuckChorris** [comment]
I much prefer this wording, though it seems perhaps a bit… rambling?

The original was succinct, and it would be nice to maintain that. It also seems like it removes the idea that a person feeling unsafe takes priority over a person feeling awkward.

It's a great start though, and a definite improvement over the current wording.

**Comment by An-Annoymous-Developer** [comment]
A principle that feeling of fear take priority over feelings of comfort could easily be added as a separate paragraph once. As for the general wording, I'd encourage you to write your own pull request and try your hand at it :)

**Comment by asiekierka** [comment]
It is a good try.

**Comment by bkeepers** [comment]
Thanks for your feedback. See https://github.com/todogroup/opencodeofconduct/issues/84.

**Pull request closed without merging**
