### PR TITLE
expand list of unprotected classes

### PR DESCRIPTION
**Pull request by sstjohn**
adds 'heterophobia' and 'pro-semitism' to the list, which currently includes 'reverse racism,' 'reverse sexism,' and 'cisphobia.'

### CODE REVIEW

**Comment by sstjohn** [comment]
hey https://github.com/todogroup/opencodeofconduct/pull/56

**Comment by An-Annoymous-Developer** [comment]
Did you intentionally make your code of conduct take Israel's side in the Israel-Palestinian war or did you just forget that the world is bigger than America. 

I would have thought that an open source conference would default to wanting to welcome both Israelis and Palestinians, that means not taking a side. 

(Late clarifying edit - things that take Israel's side in the Israel-Palestinian conflict are a subset, not a synonym, of "pro-semeticsm")

**Comment by sstjohn** [comment]
Wow, I am so not here for the opinions of goyim.

**Comment by An-Annoymous-Developer** [comment]
1) I am not a goy.
2) Most of the people the CoC explicitly seeks to include are goyim.

**Comment by sstjohn** [comment]
1) If you actually weren't a goy, you wouldn't be so comfortable eliding the distinction between semitism and zionism.
2) Surely you jest. This CoC's purpose is to protect marginalized people. Goyim are exceedingly privileged.

I don't wish to continue this conversation with you. Now go away, troll.

**Comment by An-Annoymous-Developer** [comment]
1) Not all hostility to Israel is anti-semitic but all anti-semites are hostile to Israel. The same is true in reverse, not all pro-semites are on Israel's side but being on Israel's side is a pro-semetic position - and thus protected by your revision. You'll notice I already edited by post to clarify that point before your post. 

2) Goyim are about 99.8% of the world's population, unsurprisingly that number includes everyone from the world's most privileged to it's least privileged.

**Comment by sstjohn** [comment]
You obviously don't understand Judaism or privilege at all.

Let's see if you can grasp this: I do not wish to continue to discuss this with you.

**Comment by sstjohn** [comment]
@bkeepers why was this closed?

**Comment by bkeepers** [comment]
Sorry @sstjohn, I thought you were trolling. I've been sorting through a lot of noise in this repo this week, and it's hard to tell who is being sincere.

Can you explain your thinking on why these things should be added and maybe give some examples of how they have been used to derail open source efforts?

**Comment by sstjohn** [comment]
Idk, is that really the criteria for inclusion? This list appears to be something of an inverse of protected classes, but I think it's incomplete.

I'd suggest we continue this discussion in the separate pull requests I've since opened:
https://github.com/todogroup/opencodeofconduct/pull/77
https://github.com/todogroup/opencodeofconduct/pull/78

**Comment by KelseyDH** [comment]
@sstjohn I suggest we don't try to make an exhaustive list of every [_ism_](https://en.wikipedia.org/wiki/List_of_political_ideologies), and by that I mean pointing out every single one and trying to somehow categorize an approach to every conceivable one.  If we add anti-semitism then someone is going to want islamophobia or anti-arabism, etc and I can quickly see this becoming unnecessarily contentious, especially since discrimination on the basis of religion or ethnic background is already a protected ground within the harassment document, so anti-semitic behaviour is already covered.

**Pull request closed without merging**
