### PR TITLE
clarify rationale

### PR DESCRIPTION
**Pull request by arielelkin**

### CODE REVIEW

**Comment by caniszczyk** [comment]
http://todogroup.org/blog/followup-open-code-of-conduct/

**Comment by arielelkin** [comment]
You say you will not be continuing work on writing a code of conduct, yet you publish this template for a CoC and recommend that projects consider adopting a CoC. 

I'm concerned that projects will base their CoC on a template that's no longer maintained. Do you see my point?

**Comment by caniszczyk** [comment]
@arielelkin we clearly go over our intentions in the blog post

> Many people have invested in developing codes of conduct, and our efforts are better spent supporting their work. We will not be continuing work on writing a code of conduct. We remain confident that a code of conduct is an important tool in building healthy communities, and we recommend projects consider adopting a code of conduct that fits their community.

The GitHub repo has a notice mentioning the blog post also.

This is also in line with what GitHub recommends these days:
https://help.github.com/articles/adding-a-code-of-conduct-to-your-project/

**Comment by arielelkin** [comment]
@caniszczyk: of course, I'm not disputing the usefulness of a Code of Conduct :-)

But I fail to see how the blog post addresses my concern.. Publishing a CoC, as is currently your case, implies that you encourage its adoption. Especially so if you're an entity like the TODO Group.

If you're encouraging its adoption, then you should maintain it. If you can't maintain it, then you should not encourage its adoption. This is a matter of scalability: it is a fact that societal standards of conduct change with time.

**Comment by caniszczyk** [comment]
@arielelkin it's a template, people are free to do with it what they want, we aren't maintaining this repo anymore or putting anymore energy in it (as stated in our blog post)

**Pull request closed without merging**
