### PR TITLE
Declare the paused state of the OCOC

### PR DESCRIPTION
**Pull request by DerekTurtleRoe**
Add a statement to the README to alert people of the paused status of the project.

### CODE REVIEW

**Comment by preoctopus** [comment]
:+1:

**Comment by Addvilz** [comment]
:+1:

**Comment by DerekTurtleRoe** [comment]
:+1: 

:laughing:

**Comment by giulioprisco** [comment]
:+1:

**Comment by DuaneOBrien** [comment]
+1

**Comment by DerekTurtleRoe** [comment]
We should merge this ASAP, is there somebody who can merge?

**Comment by DerekTurtleRoe** [comment]
I'm going to go ahead and close this, it seems this will be on hold for quite a while, and the maintainers seem to be busy.

**Pull request closed without merging**
