### PR TITLE
Small change to prevent misuse of identifiable info

### PR DESCRIPTION
**Pull request by DerekTurtleRoe**

### CODE REVIEW

**Comment by Addvilz** [comment]
I believe this should be extracted outside "doxing" and redefined, and expanded. Misuse of personal information is ambiguous enough and there is a lot of room for interpretation there.

**Comment by DerekTurtleRoe** [comment]
Yeah, that's true. Do you have any suggestions? Should it be it's own separate bullet point or should it be a new section, or maybe still part of the same bullet point but worded differently and expanded from there?

**Comment by Addvilz** [comment]
We should probably start by identifying the cases of potential misuse and decide on the presentation. What do you think?

Although, if you think of it, misuse has so many possible definitions - use for commercial purposes, referencing, etc. Can you maybe elaborate on what exactly did you mean by misuse of identifiable info?

**Comment by DerekTurtleRoe** [comment]
Use of personally identifiable information for commercial gain, blackmail, SWATing, to locate or harass an individual, to prevent an individual from speaking openly about any subject, to use info to put fear into the individual, to force individuals away from the community...

Those are the ones I can think of. Maybe something about digital theft, account hijacking, and posting as the stolen accounts person? Not sure, there are probably more. :smile:

**Comment by Addvilz** [comment]
Yes, these definitely sound like pretty serious problems. I think this deserves a separate bullet point, however, I would exclude obviously illegal things, like blackmail and repetitions, like harassment and intimidation. They have already been addressed in CoC.

**Comment by DerekTurtleRoe** [comment]
OK, I am actually out of town now, but I will make a change ASAP when I get stable, secure, internet again

**Comment by NuckChorris** [comment]
Under US law, an email address is considered PII, and it's also public in git.

I'm no lawyer, and I doubt it's a problem, it's just something to note.

**Comment by schminkmink** [comment]
This section is problematic because calling out harassing behavior is sometimes the only way to keep a space safe.

**Comment by asiekierka** [comment]
Is posting personal information alone classifiable as negative? I think intent should be taken into account here. Let's say my internet connection dies in a terrible accident and the contributors to my code try to reach me. One of my friends knows my private phone number and would like to share it with the community, having my permission to do so. However, by the current wording, the very *act* of posting personally identifying information of me by someone else is prohibited.

**Comment by bkeepers** [comment]
Thanks for your feedback. See https://github.com/todogroup/opencodeofconduct/issues/84.

**Pull request closed without merging**
